DROP SEQUENCE seq_ee_num;
DROP SEQUENCE seq_co_num;
DROP SEQUENCE seq_er_num;

CREATE SEQUENCE seq_ee_num
	START WITH 1
	MAXVALUE 999999
	INCREMENT BY 1
	NOCYCLE
	CACHE 20;

CREATE SEQUENCE seq_co_num
	START WITH 1
	MAXVALUE 999999
	INCREMENT BY 1
	NOCYCLE
	CACHE 20;

CREATE SEQUENCE seq_er_num
	START WITH 1
	MAXVALUE 999999
	INCREMENT BY 1
	NOCYCLE
	CACHE 20;

       
COMMIT;